name: kubeflow builder
on:
  workflow_dispatch:
    
  push:
    branches:
      - "main"
    paths:
      - "pipeline/"
      - "resume_screening"


env:
  PROJECT_ID: sonarqube-289802


jobs:

  python-build:
    name: python-build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    # - name: python
    #   working-directory: pipeline
    #   run: |-
    #     python3 main.py
    - name: gs
      working-directory: pipeline
      run: |-
        gsutil --version
        gsutil cp pipeline.json gs://knols-ml-datasets/github_demo/

  docker-build:
    name: docker-build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    
    - name: docker login 
      run: |-
        gcloud auth configure-docker

    - name: docker build
      run: |-
        IMAGE="gcr.io/${{ env.PROJECT_ID }}/nlp-builds:latest"
        echo "Building and pushing image: $IMAGE"
        docker build -t $IMAGE .
        docker tag $IMAGE gcr.io/${{ env.PROJECT_ID }}/nlp-builds:$GITHUB_SHA
        docker push "$IMAGE"
        docker push gcr.io/${{ env.PROJECT_ID }}/nlp-builds:$GITHUB_SHA



